### ISSUE TITLE
로그인 팝업이 영문 지원 이슈

### ISSUE THREAD

**Issue by Jang-Hyuk-jun** [raccoondev85/cordova-plugin-kakao-sdk#3]
안녕하세요.

Ionic에서 현재 플러그인을 사용중인데, 로그인 기능 사용 시,
카카오톡 로그인과 다른 카카오계정 로그인 이 한글로 되어 있는데,
영문으로 사용할 순 없을까요?

**Comment by raccoondev85** [comment]
답변이 늦어 죄송합니다.
현재 ios는 내부 라이브러리에서 사용하는 버튼 이미지와 텍스트를 호출하여 그대로 사용하는데요
그래서 별도의 언어 작업이 필요없이 스마트폰 언어 설정으로 변경이 됩니다.
안드로이드는 현재 멀티링궈(영어/한글) 이 지원되지않는데요, 말씀해주신 부분을 고려하여 
스마트폰 언어에 따라 한글 아니면 영어로 되어지도록 곧 업데이트 하겠습니다.
