### ISSUE TITLE
카카오링크 에러 관련..(로그인은 잘됩니다)

### ISSUE THREAD

**Issue by kotran88** [raccoondev85/cordova-plugin-kakao-sdk#4]
카카오링크 관련해서 따로 안내사항이 없어서 예제로 나온코드를 사용하였는데

Cannot find name 'KLContentObject'
이이런식으로 오브젝트가 전부 없다고 나오네요..

어떻게하면 될까요?

**Comment by raccoondev85** [comment]
답변이 늦어 죄송합니다
import 하는 부분에 

import {
...
  KLContentObject,
...
} from 'kakao-sdk';

추가하셔야하는데요
node_modules에 kakao-sdk가 있는지 확인해보시겠어요?
없으시면 npm install kakao-sdk 로 설치하시고 다시  import 부탁드립니다

**Comment by raccoondev85** [comment]
잘 안되시면 다음 링크에 제가 예제 프로젝트 올렸는데 참고부탁드려요
https://github.com/raccoondev85/cordova-plugin-kakao-sdk-example
