### ISSUE TITLE
로그인 호출시

### ISSUE THREAD

**Issue by SongKiDoo** [raccoondev85/cordova-plugin-kakao-sdk#5]
IOS에서 login API호출시 해당 로그와 함께 앱 크러쉬납니다.

Start KaKao plugin

+[NSBundle ko_appKey]: unrecognized selector sent to class 0x1eff448c0

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[NSBundle ko_appKey]: unrecognized selector sent to class 0x1eff448c0'

**Comment by SongKiDoo** [comment]
Linked Frameworks 에서 Kakao framework 3개는 등록되어 있었으나 KakaoOpenSDK.framwork가 빠져있어 추가하여 해결

**Comment by raccoondev85** [comment]
답변이 늦어서 죄송합니다.
정상적으로 ionic cordova platform add 하셨다면 linked frameworks에 자동등록이 될텐데 이상하네요
바로 답장 못드려서 다시한번 죄송합니다
