### ISSUE TITLE
cordova로 개발중인데 사용법을 모르겠어요..

### ISSUE THREAD

**Issue by ssamuelllll** [raccoondev85/cordova-plugin-kakao-sdk#6]
ionic말고 순수 cordova 예제로 사용법을 알려주실수 있으신가요?
카카오 링크를 구현해야 하는데 이 플러그인의 사용법을 모르겠어요.. ㅠㅠ

**Comment by raccoondev85** [comment]
답변이 늦어서 죄송합니다.
예제까지 첨부하여 소스에 업로드하겠습니다.
참고 부탁드려요

**Comment by raccoondev85** [comment]
https://github.com/raccoondev85/cordova-plugin-kakao-sdk-example
여기에 데모 프로젝트 올려놨으니 확인해보세요~

**Comment by ssamuelllll** [comment]
정말 감사합니다!
바쁘실텐데 감사드립니다 ㅠㅠ
 
 
-----Original Message-----
